name: Deploy to VPS

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: deploy-production
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            export PATH=$PATH:/usr/bin:/usr/local/bin
            export PROJECT_PATH=/root/omk-bot-9may
            export PM2_NAME=may9-bot

            set -e
            cd $PROJECT_PATH
            
            git fetch --all
            git reset --hard origin/main
            
            npm install --production
            
            pm2 restart $PM2_NAME --update-env || pm2 start server.js --name "$PM2_NAME"
            pm2 save
